name: Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: llvm-tools-preview

      - name: Cache cargo dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-coverage-nightly-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests with coverage
        env:
          # This flag activates the #[cfg_attr(coverage, ...)] in the code
          RUSTFLAGS: "-C instrument-coverage --cfg=coverage"
          LLVM_PROFILE_FILE: "tincre-logger-%p-%m.profraw"
        run: cargo test --all-features --all-targets --verbose

      - name: Generate coverage report with grcov
        id: grcov
        uses: actions-rs/grcov@v0.1

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Tincre/tincre-logger
          files: ${{ steps.grcov.outputs.report }}
          verbose: true
