name: coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install grcov
        run: |
          # The official Codecov example uses a direct download, which is faster.
          LATEST_GRCOV_VERSION=$(curl -s "https://api.github.com/repos/mozilla/grcov/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")' | sed 's/v//')
          curl -L "https://github.com/mozilla/grcov/releases/download/v${LATEST_GRCOV_VERSION}/grcov-x86_64-unknown-linux-gnu.tar.bz2" | tar jxf - -C /usr/local/bin

      - name: Run tests and generate coverage data
        env:
          # These flags tell the Rust compiler to generate coverage data
          RUSTFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "tincre-logger-%p-%m.profraw"
        run: |
          cargo test --verbose

      - name: Generate lcov report
        run: |
          grcov . \
            --binary-path ./target/debug/ \
            -s . \
            -t lcov \
            --branch \
            --ignore-not-existing \
            -o lcov.info

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Tincre/tincre-logger
          files: lcov.info
          verbose: true
